### ISSUE TITLE
The keys of hypertries are not copied/moved during assignment

### ISSUE THREAD

**Issue by nkaralis** [dice-group/hypertrie#41]
The assignment operator does not copy/move  the contents of the keys of the RHS hypertrie to the LHS hypertrie. In the following example, after the hypertrie _ht_ **goes out of scope** (end of if clause), the contents of its keys get deleted. _const_ht_ preserves the depth and size of _ht_, but if we try to access the contents of the keys, we get a segmentation fault.

```C++
const_Hypertrie<default_bool_Hypertrie_t> const_ht{2};
std::cout << "CONST_HT DEPTH BEFORE IF CLAUSE: " << const_ht.depth() << std::endl;
// CONST_HT DEPTH BEFORE IF CLAUSE: 2
std::cout << "CONST_HT SIZE BEFORE IF CLAUSE: " << const_ht.size() << std::
// CONST_HT SIZE BEFORE IF CLAUSE: 0
if(true) {
    Hypertrie<default_bool_Hypertrie_t> ht{3};
    ht.set({1, 10, 20}, true);
    ht.set({2, 10, 20}, true);
    ht.set({3, 10, 20}, true);
    ht.set({4, 10, 20}, true);
    ht.set({5, 10, 20}, true);
    // assignment
    const_ht = const_Hypertrie(ht);
    std::cout << "HT DATA: \n" << (std::string) ht << std::endl;
    // HT DATA:
    // [ ⟨5, 10, 20⟩ → true, ⟨1, 10, 20⟩ → true, ⟨3, 10, 20⟩ → true, ⟨4, 10, 20⟩ → true, ⟨2, 10, 20⟩ → true ]
    std::cout << "CONST_HT DATA INSIDE IF CLAUSE: \n" << (std::string) const_ht << std::endl;
    // CONST_HT DATA INSIDE IF CLAUSE:
    // [ ⟨5, 10, 20⟩ → true, ⟨1, 10, 20⟩ → true, ⟨3, 10, 20⟩ → true, ⟨4, 10, 20⟩ → true, ⟨2, 10, 20⟩ → true ]
}
std::cout << "CONST_HT DEPTH AFTER IF CLAUSE: " << const_ht.depth() << std::endl;
// CONST_HT DEPTH AFTER IF CLAUSE: 3
std::cout << "CONST_HT SIZE AFTER IF CLAUSE: " << const_ht.size() << std::endl;
// CONST_HT SIZE AFTER IF CLAUSE: 5
std::cout << "CONST_HT DATA AFTER IF CLAUSE: \n" << (std::string) const_ht << std::endl; // segmentation fault
auto first_const_ht_key = const_ht.begin(); // segmentation fault
```

Is this the proper way to copy the data of a hypertrie to another one?

**Comment by bigerl** [comment]
`const_Hypertrie` holds a non-owning reference to the internal hypertrie data-structure. 
The initialization of a depth 2 hypertrie in line 1 ` const_Hypertrie<default_bool_Hypertrie_t> const_ht{2}; ` is fine because empty tensors are not backed by any data. 
But after `const_ht = const_Hypertrie(ht);` `const_ht` is bound to a internal structure that is owned by `ht` only. When `ht` goes out of scope the internal structure is automatically cleaned up. 
Comparable to iterators in STL, the `const_ht` is invalidated when the referenced `ht` goes out of scope.
